import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

import { SearchIcon } from "lucide-react";
import Navbar from "@/components/Navbar/Navbar";
import SessionWrapper from "@/components/Wrapper/SessionWrapper";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <Providers>
            <Navbar />
            <main>
              <Toaster />
            </main>
            {children}
          </Providers>
        </body>
      </html>
    </SessionWrapper>
  );
}
